### ISSUE TITLE
Add occ command for adding a client

### ISSUE THREAD

**Issue by cortho** [owncloud/oauth2#111]
ATM it is only possible to add a new client manually by clicking in the Admin Settings.

An occ command performing this would make scriptable setups possible.

**Comment by SamuAlfageme** [comment]
Duplicate of https://github.com/owncloud/oauth2/issues/94; there's some work already going on in https://github.com/owncloud/oauth2/pull/107 - @cortho the feedback from your experience there can be quite useful. Thanks!

Also some related discussion for EE usecases: https://github.com/owncloud/oauth2/issues/72

**Comment by cortho** [comment]
Sorry I missed this, thx.
