### ISSUE TITLE
exidently deleting cliend identifier scrws up oauth

### ISSUE THREAD

**Issue by theScrabi** [owncloud/oauth2#124]
So what is my problem here:
When you delete a client id here by clicking the delete button the specified client has no access to owncloud anymore. If you want to add the client again you would have to create a new access key, copy this key into the source code of your app and recompile it, or access the OC database and restore the keys with MySQL. If a low level 0815 admin like me has the awsome idea of deleting his client ids because he has no plan how OAuth works, and maybe is also not able to compile an app/access a database, he basically screwed up oauth for his whole installation.

So maybe we should make it a little less easy to delete such client ids.

![sdfgsdg](https://user-images.githubusercontent.com/1891273/37656104-63706316-2c47-11e8-9252-770e39e2f42d.png)

**Comment by michaelstingl** [comment]
@SamuAlfageme FYI ^

**Comment by SamuAlfageme** [comment]
As an admin you have to **really want to delete** the client (https://github.com/owncloud/oauth2/issues/73) when hitting that button. 

Should also be solved either with https://github.com/owncloud/oauth2/issues/72. Also read my concerns on the matter on https://github.com/owncloud/oauth2/issues/94#issuecomment-350024020

**Comment by theScrabi** [comment]
I see, I must have clicked away that dialogue.

But maybe we should consider to make the pre-installed id's only able to disable instead of being deletable.

**Comment by michaelstingl** [comment]
Parameter in config.php to disable the default ones? Make the delete button a disable button for the default ones? Use cases without default client ID’s are very, very rare.

**Comment by SamuAlfageme** [comment]
@michaelstingl no strong opinion. 

> Use cases without default client ID’s are very, very rare. 

If you're keen on privacy and you just want your own self-/ownbrander-built clients to access this. This was my goal for the discussion on https://github.com/owncloud/oauth2/issues/72 

@theScrabi shall we close here and move the discussion to https://github.com/owncloud/oauth2/issues/72

**Comment by michaelstingl** [comment]
I definitely want to support use cases without default ids. Moving to #72 sounds good.
