### ISSUE TITLE
addClient() validations fail without error message

### ISSUE THREAD

**Issue by individual-it** [owncloud/oauth2#128]
1. give any "name" and "xxxxxxxxxx" ans redirection URI
2. click "add"

an error should be shown with a reason why the setting is not saved

**Comment by SamuAlfageme** [comment]
Fully agreed - Both validations: 

https://github.com/owncloud/oauth2/blob/487e277042bfc5da98bfa4790c6ec5cf50fbc91d/lib/Controller/SettingsController.php#L95-L101

and 

https://github.com/owncloud/oauth2/blob/487e277042bfc5da98bfa4790c6ec5cf50fbc91d/lib/Controller/SettingsController.php#L102-L108

Should get more self-explanatory messages. (Even delegate some of these to the app's frontend code).
