### ISSUE TITLE
500 error if add token with same name as existing

### ISSUE THREAD

**Issue by tomneedham** [owncloud/oauth2#135]
- enable app
 - go to admin settings
 - enter new registered client with name `iOS` and any redirection URL
 - click add
 - 500 error 💥

**Comment by individual-it** [comment]
what should happen? I guess some proper error message?

**Comment by individual-it** [comment]
the RFC says:
```
   When registering a client, the client developer SHALL:

   o  specify the client type as described in Section 2.1,

   o  provide its client redirection URIs as described in Section 3.1.2,
      and

   o  include any other information required by the authorization server
      (e.g., application name, website, description, logo image, the
      acceptance of legal terms).
```

I think the uniqueness of the name is up to owncloud requirements

**Comment by individual-it** [comment]
- [ ] create acceptance tests for that issues

**Comment by DeepDiver1975** [comment]
the name of the client is out of scope of the specs. uniqueness is part of ux from my pov.

Why would you want to add 10 clients with the name 'iOS' ? How to know which one is which?
One wants to remove a specific e.g. client version. so better name them properly 'iOS 1.1.0' 'iOS 1.2.3' .......

**Comment by DeepDiver1975** [comment]
in terms of UX: there shall be no http status code 500 ;-)

**Comment by tomneedham** [comment]
> in terms of UX: there shall be no http status code 500 ;-)

I can interpret this as: I should catch the unqiueConstraintViolation, and return some 4xx error and make it look pretty :)

**Comment by VicDeo** [comment]
Fixed by https://github.com/owncloud/oauth2/pull/237
