### ISSUE TITLE
Switch user on Login

### ISSUE THREAD

**Issue by theScrabi** [owncloud/oauth2#140]
Currently it's not quite an easy task to do if you want to login into 2 or more accounts at the same server.

Because after accessing the first account you are still loged  in your browser, and you get directly redirected to the authorise view:
![screenshot_1528803133](https://user-images.githubusercontent.com/1891273/41288133-8a939ebe-6e45-11e8-9d36-9936269105c6.png)

If you now want to login into a different account now, you have to open your browser, and log out manually.

So it might be a good idea if we had some sort of "switch user" option in the authorize screen:

![screenshot_1528802428](https://user-images.githubusercontent.com/1891273/41288238-ef255408-6e45-11e8-9fdf-c450c7e74f61.png)
All clients are effected by this [iOS/android/Desktop].

**Comment by SamuAlfageme** [comment]
@theScrabi see https://github.com/owncloud/oauth2/pull/60 and pass a `user` query param as in https://github.com/owncloud/oauth2/issues/48

Desktop does this since https://github.com/owncloud/client/pull/5907

**Comment by michaelstingl** [comment]
@SamuAlfageme Can this screen always show the name of the currently logged in user?

![41288133-8a939ebe-6e45-11e8-9d36-9936269105c6-2](https://user-images.githubusercontent.com/214010/41291523-38a077de-6e50-11e8-8ef4-bab34638c3c7.png)

(just to avoid confusion)

**Comment by SamuAlfageme** [comment]
@michaelstingl it does, yup: https://github.com/owncloud/oauth2/pull/90
