### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/oauth2#142]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.focus()`

- [x] /js/login.js

`.focus()`

- [x] /js/login.js

`.attr()`

- [x] /js/login.js

**Comment by felixheidecke** [comment]
I can't really test oAuth locally but looking at the methods used and reading up on the upgrade guide, it all will work properly.

**Comment by michaelstingl** [comment]
> I can't really test oAuth locally

why?
