### ISSUE TITLE
Error while enabling app

### ISSUE THREAD

**Issue by mrlinux1** [owncloud/oauth2#143]
I tried to enable OAuth2 app on a 10.0.9 server and got the error message:

Error while enabling app

(I think the first message was about "broken app" ?)

But when I do a occ app:list the app is enabled.
![enable_disable_oauth2](https://user-images.githubusercontent.com/9421663/43579943-0080583e-9654-11e8-9d25-aa545bf4e2a9.png)

**Comment by DeepDiver1975** [comment]
Server Log?

**Comment by mrlinux1** [comment]
[enabling.oauth.txt](https://github.com/owncloud/oauth2/files/2258496/enabling.oauth.txt)

Same procedure on the productive cloud

**Comment by mrlinux1** [comment]
After that the app is listed as enabled with a occ app:list but the web site shows that there is still an upgrade to do.
After an occ upgrade everything looks correct.

**Comment by davitol** [comment]
Enablong the app works fine for me. i guess we can close the issue
