### ISSUE TITLE
Refactor unit tests

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/oauth2#148]
- use proper asserts like assertINstanceOf, assertCount
- use response->getData instead of response->render followed by json_decode
- use data provider to simpliy the tests

**Comment by patrickjahns** [comment]
Please also make the tests more descriptive - in the sense - which function tests what and why

**Comment by DeepDiver1975** [comment]
oauth is moving out of focus with open id connect coming to town -> close
