### ISSUE TITLE
Move remaining CI from Travis to drone

### ISSUE THREAD

**Issue by phil-davis** [owncloud/oauth2#155]

**Comment by davitol** [comment]
https://github.com/owncloud/oauth2/pull/161#pullrequestreview-152394633

**Comment by paurakhsharma** [comment]
@phil-davis @individual-it, there is not `.travis.yml` file here. Close this issue?

**Comment by individual-it** [comment]
It was removed by #168

**Comment by DeepDiver1975** [comment]
Please adjust readme.md - THX
