### ISSUE TITLE
Option to protect or restore default client config

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/oauth2#163]
@soydepr opened the issue https://github.com/owncloud/ios/issues/1083 after he deleted the default set of "OAuth 2.0 Registered clients" in the "User Authentication" settings.

As a result, his iOS client can no longer connect.

@DeepDiver1975 @pmaier1 Should default client config get more protection, or should there be an option to restore the default client config?

@soydepr Do you have access to the database? @IljaN Could you help with the SQL commands to restore the default client config?

**Comment by IljaN** [comment]
@michaelstingl not sure if I understand, are you talking about the "default" client entries?

**Comment by pmaier1** [comment]
![oauth](https://user-images.githubusercontent.com/21193500/45874734-edab3f80-bd95-11e8-8b34-51c25f04c0b2.png)

Restoring the default settings should be added, IMO, yes.

**Comment by IljaN** [comment]
Executing following command should restore the default clients:
``` ./occ migrations:execute oauth2 20170329194544```

**Comment by soydepr** [comment]
Yes I have access to db. Thanks

**Comment by IljaN** [comment]
Yes execute this command inside your owncloud install directory, you should probably execute it as your webserver user like this:
```sudo -u www-data ./occ migrations:execute oauth2 20170329194544```
This will execute the script which is ran on oauth2 app install responsible for creating those entries.

**Comment by soydepr** [comment]
Command not found

**Comment by IljaN** [comment]
You need to change in to the directory where owncloud is installed

**Comment by soydepr** [comment]
I did 
![71c92e57-14d1-42fe-947e-539c43370b5e](https://user-images.githubusercontent.com/546367/45881734-0e659c00-bd7a-11e8-874e-6ccf44cd1a4d.png)

**Comment by IljaN** [comment]
"./" before occ is missing

**Comment by soydepr** [comment]
I did try that as well this is strange. Doing on phone 

![f1cfd325-b219-40ef-b9b8-3a18c44e3d83](https://user-images.githubusercontent.com/546367/45885306-1591a780-bd84-11e8-974c-f3c5b7c7d2de.png)

Will be regular oc soon

**Comment by soydepr** [comment]
Same from pc. Command not found is it complaining about migrations:execute ?

**Comment by soydepr** [comment]
What now 
![ba83c3da-446f-46b2-8ac9-31fe5d6a8274](https://user-images.githubusercontent.com/546367/45890110-2516ed80-bd90-11e8-8d76-1a6d7ac4448c.png)

**Comment by DeepDiver1975** [comment]
fixed by https://github.com/owncloud/oauth2/pull/166/commits/865f6231055d75ac18c2a84c083b5992ae680f94 - an occ command to add clients was added
