### ISSUE TITLE
OAuth 0.4.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/oauth2#191]
When taking care of a task (and marking as done), please add your name to the task!

### Reason

- Release needed for user switch: https://github.com/owncloud/oauth2/pull/188

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version" 
- [x] Create "0.4.0 Testplan" @davitol https://github.com/owncloud/oauth2/issues/193

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries: https://github.com/owncloud/oauth2/releases/tag/v0.4.0
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [ ] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number => https://github.com/owncloud/oauth2/pull/196

**Comment by PVince81** [comment]
@davitol RC tarball ready to test: https://github.com/owncloud/oauth2/releases/tag/v0.4.0RC1

**Comment by davitol** [comment]
@PVince81 tarball is QA-ready

**Comment by PVince81** [comment]
final tarball here, same as RC (no need to retest): https://github.com/owncloud/oauth2/releases/tag/v0.4.0
