### ISSUE TITLE
Problem related to User-Key based encryption

### ISSUE THREAD

**Issue by albansch** [owncloud/oauth2#213]
Hi,

(this might not be a valid scenario, nevertheless I thought it would solve some limitations of TOTP -> mostly related to the inability to connect via apps anymore once enabled)

Basically tried to have both TOTP & OAUTH2 on the same owncloud instance.
The reason of such approach:
- TOTP secure the web portal access through URL
- OAUTH2 secure the remote app access (such as the desktop client)

Unfortunately, as long as TOTP is active, any sync request from the pre-authorized desktop client returns an error.

### Steps to reproduce
1. Install both TOTP & OAUTH2
2. Login with a user, enable both TOTP & OAUTH2
3. When setting up the user for Dekstop Client, proceed with OAUTH2 authentication
4. Then the desktop client returns 403 errors when trying to download files

### Expected behaviour
The client shall work find - the OAUTH2 shall bypass the TOTP auth layer.

### Actual behaviour
the desktop client returns 403 errors when trying to download files

### Server configuration

Centos 7
Nginx 1.12.2
MariaDB 5.5.60
PHP 5.4.16
Owncloud 10.1
Updated from an older ownCloud
Where did you install ownCloud from: owncloud repo

**Comment by michaelstingl** [comment]
With proper OAuth 2.0 setup, desktop sync client opens the default web browser on you system. You use the web UI for login. With TOTP installed, you’ll need to enter the 2nd factor in a next step. After this, the sync client is authorized.

Maybe a PHP module is missing on the server. Please check the docs. (I‘m no Nginx expert. Did you try Apache?)

Also the PHP 5.4 is EOL for a long time and not sufficient for ownCloud 10.1.

**Comment by albansch** [comment]
thx for the feedback, have tried with PHP 7.2, same behaviour.

The OAuth 2.0 flow is fine and confirmed.

The TOTP flow, unfortunately, doesn't allow client sync -> it just says that access through client is disabled and you have to use the web UI.

Therefore, I was looking at using both OAuth 2 and TOTP combined, to enable 2 factor on the web UI, and OAuth 2 for desktop client.

**Comment by michaelstingl** [comment]
> The TOTP flow, unfortunately, doesn't allow client sync -> it just says that access through client is disabled and you have to use the web UI.

Where do you see this? Could you post screenshots how the steps look like?

**Comment by albansch** [comment]
See following screenshots:

[https://ibb.co/xM8xR3H](Step 1)
Link 1 location: https://domainofowncloudinstance.com/index.php/settings/personal?sectionid=security#apppasswords
 
[https://ibb.co/wRFGy3x](Step 2)
Link 1 location: https://domainofowncloudinstance.com/index.php/settings/personal?sectionid=security#apppasswords
Link 2 Location: https://domainofowncloudinstance.com


I actually figured out that if you use Link 1 and create an app token, then use the credentials from the token with the dekstop client, you can authenticate without the error shown in step 2. I was hoping that oAuth would act at this stage if both TOTP and OAUTH are installed.

**Comment by michaelstingl** [comment]
@albansch If you see the user and password fields as shown in the screenshot from `STEP1`, the ownCloud desktop sync client can't detect OAuth 2.0 capabilities from the ownCloud server. After entering the server URL, the ownCloud desktop sync client should open the system browser.

As mentioned earlier, I'd assume the server isn't setup properly. For Apache, ownCloud and OAuth 2.0 relies on this:
- https://doc.owncloud.com/server/10.1/admin_manual/installation/manual_installation.html#additional-apache-configurations
- https://doc.owncloud.org/server/10.1/admin_manual/configuration/general_topics/general_troubleshooting.html#oauth2

Please check if you have the related Nginx features enabled.

**Comment by albansch** [comment]
@michaelstingl you are right, the example provided were without OAUTH 2 enabled.

If I enable OAUTH 2:

1. Dekstop client > enter owncloud server URL
2. Browser > redirection to browser, login with username/password
3. Browser > provided TOTP code
4. Browser > message confirms OAUTH 2 has been enabled for client
5. Desktop client > at first sync, error downloading/uploading files as per [https://ibb.co/RcqyL5c](url)

If I disabled TOTP app, then no error at step 5. This is where I do mention that there is a conflict when both TOTP & OAUTH 2 are enabled.

**Comment by michaelstingl** [comment]
@albansch Did you check your server config?

Please also post some debug log from the errors in your screenshot. ([more info](https://doc.owncloud.org/desktop/2.6/troubleshooting.html#log-files))

**Comment by albansch** [comment]
@michaelstingl yes, checked my server config, fastcgi_param Authorization $http_authorization is there.
here are the logs - appears to be a problem with encryption actually:

```
NGINX Access log:
INTERNAL-SERVER-IP - - [25/Jun/2019:06:39:27 +0200] "GET /remote.php/dav/files/owncloudtest@domainofowncloud.com/Photos/Squirrel.jpg HTTP/1.0" 403 6613 "-" "Mozilla/5.0 (Windows) mirall/2.5.3 (build 11250)" "CLIENT-REMOTE-IP"

OWNCLOUD log:
{"reqId":"eb0f04b6-4668-42a7-9f3b-857f873dccca","level":0,"time":"2019-06-25T06:39:27+02:00","remoteAddr":"CLIENT-REMOTE-IP","user":"owncloudtest@domainofowncloud.com","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"GET","url":"\/remote.php\/dav\/files\/owncloudtest@domainofowncloud.com\/Photos\/San%20Francisco.jpg","message":"updating token 40930, last check is now 1561436949"}

{"reqId":"eb0f04b6-4668-42a7-9f3b-857f873dccca","level":0,"time":"2019-06-25T06:39:27+02:00","remoteAddr":"CLIENT-REMOTE-IP","user":"owncloudtest@domainofowncloud.com","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/owncloudtest@domainofowncloud.com\/Photos\/San%20Francisco.jpg","message":"Exception: HTTP\/1.1 403 Encryption not ready: Private Key missing for user: please try to log-out and log-in again: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Message\":\"Encryption not ready: Private Key missing for user: please try to log-out and log-in again\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(288): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":401}"}
```

**Comment by albansch** [comment]
As stated here https://doc.owncloud.com/server/admin_manual/configuration/files/encryption/encryption_configuration.html
Oauth2 doesn't work with User-Key Based Encryption, hence my issue.
