### ISSUE TITLE
Refresh token expiry?

### ISSUE THREAD

**Issue by crspybits** [owncloud/oauth2#217]
Hi-- I'd like to know how long refresh tokens last for with ownCloud Oauth2. This doesn't seem standard across different OAuth2 providers (e.g., for Box, the refresh tokens last for 60 days or until used to refresh the access token-- https://community.box.com/t5/Platform-and-Development-Forum/Refresh-Token-Expiring-in-1-hour/td-p/4735; but with Google, the refresh tokens have a far longer duration). Thanks!

**Comment by michaelstingl** [comment]
> Hi-- I'd like to know how long refresh tokens last for with ownCloud Oauth2.

Access token expires after 60 minutes, but the refresh token never expires. It gets invalidated after use.

**Comment by crspybits** [comment]
After a single use? Sounds like the Box model of refresh tokens then.

**Comment by michaelstingl** [comment]
> After a single use?

yes
