### ISSUE TITLE
Oauth 0.4.2

### ISSUE THREAD

**Issue by micbar** [owncloud/oauth2#230]
### Reason

- https://github.com/owncloud/oauth2/pull/229

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.4.2 Testplan" @davitol https://github.com/owncloud/oauth2/issues/231

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Check/adapt info.xml stuff
- [x] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => @davitol https://github.com/owncloud/oauth2/issues/231

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable) @davitol 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by DeepDiver1975** [comment]
All changes since 0.4.1: https://github.com/owncloud/oauth2/compare/v0.4.1...master

**Comment by micbar** [comment]
RC1 in https://github.com/owncloud/oauth2/releases/tag/v0.4.2RC1

**Comment by micbar** [comment]
@davitol We should include https://github.com/owncloud/oauth2/pull/225 in the Release

**Comment by micbar** [comment]
RC3 https://github.com/owncloud/oauth2/releases/tag/v0.4.2RC3

Included #225

**Comment by davitol** [comment]
> RC3 https://github.com/owncloud/oauth2/releases/tag/v0.4.2RC3

@micbar RC3 tarball is QA ready. Test results and relevant info in: https://github.com/owncloud/oauth2/issues/231

**Comment by micbar** [comment]
@davitol Final https://github.com/owncloud/oauth2/releases/tag/v0.4.2

**Comment by davitol** [comment]
> @davitol Final https://github.com/owncloud/oauth2/releases/tag/v0.4.2

Sanity tested and works. 👍
