### ISSUE TITLE
Cannot add OAuth 2.0 new clients using 0.4.1.RC1 version

### ISSUE THREAD

**Issue by davitol** [owncloud/oauth2#232]
### Steps to reproduce
1. Try to add a new client

![oauth2ClientBug](https://user-images.githubusercontent.com/10596560/68862580-ff644a80-06ed-11ea-9c76-a2997cca861e.gif)

### Expected behaviour
The client is added

### Actual behaviour

You are redirected to a blank page (http://server/apps/oauth2/clients) and a log is spotted
```
{"reqId":"qSwGXFjhwlchlvgRgKdD","level":3,"time":"2019-11-14T13:41:23+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"POST","url":"\/apps\/oauth2\/clients","message":"require_once(\/mnt\/data\/apps\/oauth2\/lib\/..\/vendor\/autoload.php): failed to open stream: No such file or directory at \/mnt\/data\/apps\/oauth2\/lib\/Utilities.php#22"}
{"reqId":"qSwGXFjhwlchlvgRgKdD","level":3,"time":"2019-11-14T13:41:23+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"POST","url":"\/apps\/oauth2\/clients","message":"require_once(): Failed opening required '\/mnt\/data\/apps\/oauth2\/lib\/..\/vendor\/autoload.php' (include_path='\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/custom') at \/mnt\/data\/apps\/oauth2\/lib\/Utilities.php#22"}
```

Note: Tested with current oauth version (0.4.1) in market and works. So it is a regression

**Comment by DeepDiver1975** [comment]
Did you install from git and missed to run composer?

**Comment by davitol** [comment]
> Did you install from git and missed to run composer?

No, via tarball: https://github.com/owncloud/oauth2/releases/download/v0.4.2RC1/oauth2-0.4.2RC1.tar.gz  

and ```occ market:install -l oauth2-0.4.2RC1.tar.gz ```

**Comment by DeepDiver1975** [comment]
Is the folder vendor in the tar?

**Comment by davitol** [comment]
> Is the folder vendor in the tar?

Nope, it was not included

**Comment by davitol** [comment]
Vendor folder is new and was not included in make routine.
@micbar will fix it and create a new one tomorrow. Thanks for the hints

**Comment by micbar** [comment]
Should be fixed https://github.com/owncloud/oauth2/releases/tag/v0.4.2RC2
