### ISSUE TITLE
Authorization page is not loaded (0.4.2)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/oauth2#241]
Reproducible with tag `v0.4.2 `and newer.  `v0.4.1` works fine.

### Steps to reproduce
1. With any client (iOS, Android, desktop client) try to login using an OAuth2 server (i tested with http url)
2. Web is raised up. Enter correct credentials

### Actual behaviour
Authorization web is not displayed under an 500 error. This is the flow in iOS (same in Android and desktop):

| App | Credentials OAuth2 | Authorization OAuth2 |
| :-: |  :-:  |  :-:  |
|![Screenshot 2019-12-10 at 10 53 03](https://user-images.githubusercontent.com/14894746/70519471-44886a80-1b3c-11ea-84a6-5b91ec5e07d7.png)|![Screenshot 2019-12-10 at 10 53 26](https://user-images.githubusercontent.com/14894746/70519473-45210100-1b3c-11ea-8c28-b28c2cb0b36d.png)|![Screenshot 2019-12-10 at 10 53 37](https://user-images.githubusercontent.com/14894746/70519475-45210100-1b3c-11ea-8792-2187218d3f27.png)

Error returned in clients is `500 Internal Server error` 

owncloud logs:

> {"reqId":"ZYL8KEs75itaKwK1M24e","level":3,"time":"2019-12-10T10:15:26+00:00","remoteAddr":"172.17.0.1","user":"user1","app":"PHP","method":"GET","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc:\/\/ios.owncloud.com&client_id=X","message":"require_once(\/var\/www\/owncloud\/apps\/oauth2\/lib\/..\/vendor\/autoload.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/apps\/oauth2\/lib\/Utilities.php#22"}
> {"reqId":"ZYL8KEs75itaKwK1M24e","level":3,"time":"2019-12-10T10:15:26+00:00","remoteAddr":"172.17.0.1","user":"user1","app":"PHP","method":"GET","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc:\/\/ios.owncloud.com&client_id=X","message":"require_once(): Failed opening required '\/var\/www\/owncloud\/apps\/oauth2\/lib\/..\/vendor\/autoload.php' (include_path='\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/custom') at \/var\/www\/owncloud\/apps\/oauth2\/lib\/Utilities.php#22"}
> 

### Expected behaviour
Authorization flow completed.

### Server configuration

- **Operating system**: Android 9, iOS 13
- **ownCloud version:** (see ownCloud admin page): 10.3.1
- **Updated from an older ownCloud or fresh install:** fresh install
- **Where did you install ownCloud from:** 
- **Signing status (ownCloud 9.0 and above):**

**Comment by DeepDiver1975** [comment]
> "require_once(/var/www/owncloud/apps/oauth2/lib/../vendor/autoload.php): failed to open stream: No such file or directory at /var/www/owncloud/apps/oauth2/lib/Utilities.php#22"}

Is the oauth2 app installed from tar ball or from git?

**Comment by DeepDiver1975** [comment]
git: run composer or make
tar ball: it is broken

**Comment by DeepDiver1975** [comment]
> tar ball: it is broken

which should have been addressed by this https://github.com/owncloud/oauth2/commit/9d627b233a29251ec0a246af0931cd82ba8ba7e0

@micbar ^

**Comment by jesmrec** [comment]
> Is the oauth2 app installed from tar ball or from git?

from git

**Comment by DeepDiver1975** [comment]
> from git

better run make ;-)
