### ISSUE TITLE
oauth2 0.4.4

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/oauth2#256]
### Reason

- [x] #255

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" https://github.com/owncloud/oauth2/issues/257

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [ ] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol RC1 available in https://github.com/owncloud/oauth2/releases/tag/v0.4.4RC1

**Comment by michaelstingl** [comment]
Lowered priority. Please raise priority if needed…

**Comment by DeepDiver1975** [comment]
> Lowered priority. Please raise priority if needed…

afaik critical for the ocis-proxy to allow migration .... @butonic is to judge on this

**Comment by michaelstingl** [comment]
For test setups, the RC1 should be sufficient?

**Comment by jnweiger** [comment]
blocked by openidconnect setup

**Comment by davitol** [comment]
For testing oauth2 + OpenID connect stuff we should follow the steps documented here: https://owncloud.github.io/ocis/bridge/

**Comment by jnweiger** [comment]
@IljaN refers to https://github.com/owncloud-docker/compose-playground/blob/master/examples/migration/docker-compose.yml
... to be reworked into a testbed ...

**Comment by jnweiger** [comment]
> For testing oauth2 + OpenID connect stuff we should follow the steps documented here: https://owncloud.github.io/ocis/bridge/

No more.
use compose-playground/examples/hetzner-deploy/make_openidconnect_test.sh instead :-)

**Comment by jnweiger** [comment]
Tested with android, iOS and desktop as part of the oauth2 -> openidconnect migration scenario in https://github.com/owncloud/openidconnect/issues/66#issuecomment-709999406

Looks fine. Suggest to build the final without further ado.

**Comment by jnweiger** [comment]
Issues found while testing:
* https://github.com/owncloud/client/issues/8186

**Comment by jnweiger** [comment]
release branch merged back to master. closing :tada:
