### ISSUE TITLE
0.4.4 test run

### ISSUE THREAD

**Issue by jnweiger** [owncloud/oauth2#262]
## Test Run Document

References:
 * https://github.com/owncloud/oauth2/wiki/OAuth-code-Flow-Sequence-Diagram
 * Test plan: https://github.com/owncloud/oauth2/issues/257
 * Test suites:
    - https://github.com/owncloud/QA/blob/master/Server/Test_Plan_OAuth2.md
    - TODO: Test plan for openIDConnect
 * Release ticket: https://github.com/owncloud/oauth2/issues/256
 * Automated tests
   - oauth2 Acceptance tests https://drone.owncloud.com/owncloud/oauth2/1020/10/1
   - openidconnect (only unit tests) https://github.com/owncloud/openidconnect/tree/master/tests
 * openidconnect playground: https://github.com/owncloud-docker/compose-playground/tree/master/kopano/konnect

Versions used: 
 * https://github.com/owncloud/oauth2/releases/download/v0.4.4RC1/oauth2-0.4.4RC1.tar.gz
 * https://github.com/owncloud/openidconnect/releases/download/v0.2.0/openidconnect-0.2.0.tar.gz
 * https://download.owncloud.org/community/owncloud-10.4.0.tar.bz2

### OAuth2 app Test Plan

This aims to be a client-agnostic testplan for the OAuth2 application, centered in the actions available in the webUI and/or `occ` commands and their impact on ownCloud's core behavior. To test the application from a client standpoint see:

- Desktop Sync client: https://github.com/owncloud/QA/pull/473
- Mobile client: https://github.com/owncloud/QA/pull/474

#### Testing functionality

| Test Case | Expected Result | Result | Related Comment |
| --------- | --------------- | ------ | --------------- |
| **CLI commands** | | |
| Enable OAuth2 app via CLI using `occ app:enable oauth2` | - The apps gets enabled <br> - Replies from the WebDAV endpoint includes a new `WWW-Authenticate: Bearer...` header | :heavy_check_mark: | |

* Step 1) enable, logout, login admin, admin  check personal -> security 
   *no applications authorized.*
* Step 2) logged out. expect:<br>
  `curl -I http://$SERER/remote.php/webdav | grep -i www-auth`<br>
  *www-authendicate: bearer*

|  |  |  |  |
| --------- | --------------- | ------ | --------------- |
| Disable OAuth2 app via CLI using `occ app:disable oauth2` | - The apps gets disabled <br> - Previously mentioned header goes away in further requests | :heavy_check_mark: : | |

*  `curl -I http://$SERER/remote.php/webdav | grep -i www-auth`<br>
  *www-authenticate: basic ...*

|  |  |  |  |
| --------- | --------------- | ------ | --------------- |
| **Registered Clients** | | |
| Default clients | The default Registered clients are included among the "Settings > Admin > User Authentication" OAuth 2.0: Registered Clients | :heavy_check_mark: | See https://github.com/owncloud/oauth2/pull/38 for the default values |
| Register new Client | 64-character-length `client_id` and `client_secret` are generated together with a (required) Client Name and a (required) Redirection URL | :construction: | the name is not optional ->https://github.com/owncloud/QA/pull/646 |
| Remove a Client | - Confirmation dialog is prompted before removal <br> - All client sessions opened from those clients get removed | :no_entry: | is removed without confirmation dialog |
| **Unregistered Clients** | | |
| Authentication flow from an unregistered client | Unsuccessful [Authorization Request] | :gear: | Browser displays the "Request not valid" screen.|
| Steps: <br>1. enter URL at desktop client, hit next.<br> 2 client redirects to browser, change client_id in url to something different. Hit enter again. |
| **Authorized Applications** | | |
| Login with a Registered Client | The Client Name is displayed amongst the "Personal > Security" OAuth 2.0 Authorized Applications | :gear: | |
| Session Revocation (i.e. delete Authorized Application) | All the sessions opened in the clients are revoked and must be re-authorized | :gear: | |
| **User Account Handling** | | |
| Password change | Open sessions are revoked and new credentials must be used in further login attempts | :heavy_check_mark: | Improvement suggestion: desktop client 2.6.1 only displays a 'cannot find folder message'  when re-auth is required. |
| **Authorization Flow** | | |
| Successful [Authorization Request] without any session open in the browser | Login form with an additional informative note about the application requesting access to ownCloud is displayed | :gear: | |
| Successful [Authorization Request] with a valid session in the browser | The "Authorize" screen is displayed | :gear: | |
| Successful [Authorization Request] in a browser with a different user logged in | The "Switch User" screen is displayed, allowing to modify the current session | :gear: | See use of the additional `user` parameter in: https://github.com/owncloud/oauth2/pull/67 |
| Failed attempt in the authorization login form | The query parameters for the [Authorization Request] are preserved in next attempts | :gear: | See original issue in: https://github.com/owncloud/core/issues/28129 |
| **Relevant Smoke Tests** | | |
| Unauthenticated Actions: Public File Drop | Files get uploaded normally | :construction: | See https://github.com/owncloud/oauth2/pull/100 |

[Authorization Request]: https://github.com/owncloud/oauth2/#protocol-flow

### openidconnect app Test Plan

*TODO*

**Comment by jnweiger** [comment]
Test setup for running openidconnect together with an oauth release candidate version:
```
git clone git@github.com:owncloud-docker/compose-playground
cd compose-playground


export KOPANO_KONNECT_DOMAIN=konnect.docker-playground.local
export OWNCLOUD_DOMAIN=owncloud.docker-playground.local
export OWNCLOUD_HTTP_PORT=9680

docker-compose \
    -f owncloud-base.yml \
    -f owncloud-official.yml \
    -f owncloud-exported-ports.yml \
    -f cache/redis.yml \
    -f database/mariadb.yml \
    -f ldap/openldap.yml \
    -f ldap/openldap-mount-ldif.yml \
    -f ldap/openldap-autoconfig-base.yml \
    -f kopano/konnect/docker-compose.yml \
    up

**Comment by jnweiger** [comment]
The login screen should offer kopano as an Alternative login, as e.g. seen on
https://oidc-workshop.owncloud-demo.com/oc10/login
![image](https://user-images.githubusercontent.com/1108546/80367608-b3682500-888b-11ea-8a36-9dd7990a9674.png)

**Comment by jnweiger** [comment]
Structure visualization from the above compose
![docker-compose svg](https://user-images.githubusercontent.com/1108546/80918664-65a95c00-8d66-11ea-9820-7ce1aa71eb63.png)

**Comment by davitol** [comment]
> The login screen should offer kopano as an Alternative login, as e.g. seen on
> https://oidc-workshop.owncloud-demo.com/oc10/login
> ![image](https://user-images.githubusercontent.com/1108546/80367608-b3682500-888b-11ea-8a36-9dd7990a9674.png)

I guess this configuration should be done in config.php file in the line:

https://github.com/owncloud/core/blob/master/config/config.sample.php#L247

**Comment by davitol** [comment]
Having a oC 10.4.1 server, trying to test oauth2 0.4.4 and openideconnect having both enable using https://owncloud.github.io/ocis/bridge/#how-to-do-it.


When I run this step: https://owncloud.github.io/ocis/bridge/#check-it-is-up-and-running
```
ldapsearch -x -H ldap://XXXXXX:9125 -b dc=example,dc=com -D "cn=admin,dc=example,dc=com" -W '(objectclass=posixaccount)'
Enter LDAP Password:
ldap_bind: Invalid credentials (49)
```

![Screenshot 2020-05-05 at 17 46 30](https://user-images.githubusercontent.com/10596560/81144110-ade99980-8f73-11ea-91e5-047b19ccfcb4.png)


the credentials i am trying are the ones from the oC user admin/admin


glauth is configured to use owncloud as a backend. It was launched like this:

`bin/ocis-glauth --log-level debug server --backend-server https://myowncloudserver.com --backend-basedn dc=example,dc=com`

graphapi: 0.0.1 app is installed and enabled

`curl https://cloud.example.com/apps/graphapi/v1.0/users/admin -u admin:admin -v` works and returns 200 OK .

**Comment by davitol** [comment]
This comment https://github.com/owncloud/oauth2/issues/262#issuecomment-624466154 was solved in https://github.com/owncloud/ocis/pull/248
