### ISSUE TITLE
oauth2 can not go down next step

### ISSUE THREAD

**Issue by Xipro** [owncloud/oauth2#287]
After enabling oauth2 in owncloud, I log in with the latest desktop application, and then jump to the web page. After login authorization, the web page displays "the application has been successfully authorized". Now you can close this window. "

But the "next step" of my win application is still gray, there is no way to continue to go down.

**Comment by michaelstingl** [comment]
Looks like [another issue](https://github.com/owncloud/android/issues/3195#issuecomment-815652108) we usually see with Apache modules missing.

> 	If you want to use the OAuth2 app, then `mod_headers` must be installed and enabled.

You should really have a closer look at your server setup. Or does your proxy remove some headers from the requests?

**Comment by Xipro** [comment]
I really install the mod_headers in apache, and when not use proxy, the issue is steal appear.

**Comment by Xipro** [comment]
I fix my sever conf and thank you very much.
