### ISSUE TITLE
OAuth2 0.5.0

### ISSUE THREAD

**Issue by pmaier1** [owncloud/oauth2#299]
### Reason
- [x] https://github.com/owncloud/oauth2/pull/298
- [x] https://github.com/owncloud/oauth2/pull/286
- [x] https://github.com/owncloud/oauth2/pull/276
- [x] https://github.com/owncloud/oauth2/pull/279
- [x] https://github.com/owncloud/oauth2/pull/273

### Product approval

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/oauth2/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/oauth2 should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.5.0 Testplan"  -> https://github.com/owncloud/oauth2/issues/301
### Documentation

- [x] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan
   - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
   - [x] Do changelog tests
   - [x] Do regression tests
   - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [ ] Adapt oC Web with oC 10 documentation to reflect the new feature (notify @pmaier)
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by mmattel** [comment]
I see at least some new occ commands --> docs relevant!
@EParzefall fyi

**Comment by jnweiger** [comment]
RC1 built: https://github.com/owncloud/oauth2/releases/tag/v0.5.0-rc1
