### ISSUE TITLE
Wanted: Maintainers

### ISSUE THREAD

**Issue by joneug** [owncloud/oauth2#31]
This app was developed by a project seminar team of the University of Münster. Because of time restrictions this repository cannot be maintained by this team in the future. So maintainers are needed.

CC: @DeepDiver1975 @butonic

**Comment by DeepDiver1975** [comment]
@joneug @lukebier @dennismeis @NinaHerrmann we at owncloud happily take over maintenance of your great work.

Would it be possible for you to sign our contributors license agreement?


Signing the cla is pretty easy:
1. open a pull request with a trivial change
2. the cla assistant will popup in the pull request
3. click the button and accept the cla

in case you want to read the cla before accepting (which is encouraged ;-) ): https://owncloud.org/contribute/agreement/

Thanks a lot

**Comment by joneug** [comment]
> we at owncloud happily take over maintenance of your great work.

Thanks! This is great! 👍

> Would it be possible for you to sign our contributors license agreement?

Done.
