### ISSUE TITLE
No access to OCS API.

### ISSUE THREAD

**Issue by ogoffart** [owncloud/oauth2#33]
In my prototype implementation for the desktop client, i can successfully do PROPFIND on webdav endpoint, but ocs/v1.php/cloud/capabilities or ocs/v1.php/cloud/user returns 404.

The token needs to grant permission to the OCS API as the client uses it.

**Comment by joneug** [comment]
Which ownCloud version do you use?

**Comment by ogoffart** [comment]
the master branch

**Comment by ogoffart** [comment]
My bad,  apparently the branch was too old.
I updated to the latest master and it works fine.
