### ISSUE TITLE
"Authentication successful" page on the server

### ISSUE THREAD

**Issue by ogoffart** [owncloud/oauth2#34]
It would be nice if the app could provide an HTML page to be displayed when the user logged on successfully. The client's redirect_url would redirect to this page. And it would have a message such as: "Client authentication was successful, you can now close this tab".

Rationale: The client would use an trivial embedded webserver on localhost for the redirect_uri, but it would be much more work to serve html, css, and everything from the client. (not to mention branding issues). It would be better to have this simple page ready on the server. 

I don't want to simply redirect to the index.php main page because then suddenly the user will see the files, and might not understand that the flow needs to continue in the client.

If needed, the client can provide arguments in a GET parameter.

**Comment by guruz** [comment]
Right now the client displays an unthemed black/white HTML
https://github.com/owncloud/client/commit/3d93527a8eda3902486a678a1ed83b23726b3826#diff-f3b5ef1e3c83ae293fff051fec3aca0cR66

About what @ogoffart mentions above, maybe similar in style to "Do you really like to authorize the application “Desktop Client”?" or so?

Maybe @lukebier @joneug want to do this?

**Comment by joneug** [comment]
This is a very simple page showing the message. Right now everyone knowing the URL can see the page which I think is no problem (or do you have another opinion?).

Additionally we could include the URL to this page in the Access Token response so the clients don't need to store them statically. What do you think?

**Comment by ogoffart** [comment]
Having it as part of the access token response would indeed not be a bad idea.

**Comment by ogoffart** [comment]
It could also useful to have it in case of errors.

Some error that might occurs:
 - The client secret id is wrong
 - The code= is invalid
 - Anything else that can cause the grant_type=authorization_code to have an error.

There are more errors that can occurs but does not make sense to return them in the access token reply, for example when our embedded server is throwing a 404. Or when the login is not the login we expect ("You just logged on your client, with user 'bob', but the client was configured with the 'alice' account, please log in with that account")

But having only a page for the sucesfull auth would be good

**Comment by ogoffart** [comment]
The authorisation successful message works fine.
Another issue was created to add more messages for error cases: https://github.com/owncloud/oauth2/issues/58
