### ISSUE TITLE
Make it work with all endpoints used by clients

### ISSUE THREAD

**Issue by davivel** [owncloud/oauth2#35]
Bearer token is not valid to authenticate in next paths:

```/ocs/v1.php/cloud/user```
```/ocs/v1.php/cloud/capabilities```

(My test environment had problems with server configuration before, could be more of the same).

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Can I get the request and the response? THX

**Comment by joneug** [comment]
Similar problem like #33?

**Comment by davivel** [comment]
> Similar problem like #33?
No. I'm getting a 401.

> Can I get the request and the response? THX
I'll get them

**Comment by joneug** [comment]
Do you use Apache 2? By default it prevents Bearer Authentication (see [here](http://stackoverflow.com/questions/40225826/can-apache-prevent-bearer-authentication-header)).

**Comment by DeepDiver1975** [comment]
> Do you use Apache 2? By default it prevents Bearer Authentication (see here).

we had this issue - mod rewrite was not enabled on the test system. But this issue still happens afaik

**Comment by davivel** [comment]
It's stranger than I though. See next pictures - request and response each of them. First one happens while refreshing the root folder right after logging-in the account. Second one happens some seconds later, after going into a subfolder and back to root folder (the Android app checks capabilities every time the root folder is browsed into).

Yesterday I though that the first request didn't have the session cookie, that bearer token was failing to authenticate and that second request succeeded because it had the session cookie. But I just repeated the test, and both have the session cookie - the same one.

Same behaviour happens with requests to user endpoint, in the same moments.

![capabilities_bearer__401](https://cloud.githubusercontent.com/assets/2225614/24494052/333a01ee-1531-11e7-9877-ce0b83abc870.png)

![capabilities_200](https://cloud.githubusercontent.com/assets/2225614/24494058/398be67a-1531-11e7-89bb-d9a44d7d10f6.png)

**Comment by ogoffart** [comment]
This looks like the same problem as #33
Make sure you have a recent enough owncloud?  Which sha1 are you using?

**Comment by davivel** [comment]
Admin says ```v10.0.0beta```, so should be 0fa955380fe9a872ee1a8bd6e820d0042cad5174 .

For oauth2 app it's 6544afaddcdcfbdd0523c468c5dc559f614ef1bf

**Comment by davivel** [comment]
This was fixed with https://github.com/owncloud/core/pull/27565 .
