### ISSUE TITLE
Cannot enable app on OracleDB. 

### ISSUE THREAD

**Issue by Emil-G** [owncloud/oauth2#41]
Hi!

So i tried to enable this app (9.1.15) on a server connected to a oracle DB.

The first error it tossed was:
`An exception occurred while executing 'CREATE SEQUENCE "oc_oauth2_authorization_codes_SEQ" START WITH 1 MINVALUE 1 INCREMENT BY 1': ORA-00972: identifikatoren er for lang`

Now, when trying agian the error is related to that the object is created already:

`An exception occurred while executing 'CREATE TABLE "oc_oauth2_clients" ("id" NUMBER(10) NOT NULL, "identifier" VARCHAR2(64) NOT NULL, "secret" VARCHAR2(64) NOT NULL, "redirect_uri" VARCHAR2(2000) NOT NULL, "name" VARCHAR2(80) NOT NULL, "allow_subdomains" NUMBER(1) DEFAULT '0' NOT NULL, PRIMARY KEY("id"))': ORA-00955: det finnes allerede et objekt med det navnet`

apache@server:/var/www/html/owncloud> ./occ status
  - installed: true
  - version: 9.1.5.2
  - versionstring: 9.1.5
  - edition: Enterprise

To me, this seems like an issue related to the DB that I am using.  Does anyone have a fix for this? 

Cheers,
Emil

**Comment by Dagefoerde** [comment]
Yes, this is an issue with Oracle DB which imposes a maximum length on table names (28 chars) and field names (30 chars). I can't find an Oracle document stating this, but Moodle basically deals with the same issue, cf. https://github.com/moodle/moodle/blob/master/lib/xmldb/xmldb_table.php#L40-L47. `oc_oauth2_authorization_codes_SEQ` (33 chars) is too long. How does ownCloud normally handle these limitations?

**Comment by DeepDiver1975** [comment]
work is on-goning in here - https://github.com/owncloud/oauth2/pull/42

**Comment by michaelstingl** [comment]
@DeepDiver1975 Is https://github.com/owncloud/oauth2/pull/42 ready for a test-drive? @Emil-G do you have a chance to run the pull request on a test instance?

00007759

**Comment by felixboehm** [comment]
#42 merged, please test and reopen if you find still an issue
