### ISSUE TITLE
Request access-token

### ISSUE THREAD

**Issue by Krassmus** [owncloud/oauth2#44]
Hi there!

The readme says:

> With the Authorization Code the client can request an Access Token using the Access Token URL. Client Authentication is done using Basic Auth with the client identifier as username and the client secret as password. The following URL parameters have to be specified: ...

Isn't it so that the OAuth spec is actually different? https://tools.ietf.org/html/rfc6749#section-4.1.3

It says that the parameters need to be the payload of a (POST-) request body - not part of the URL itself. Also there is nothing that describes a basic-auth mechanism to send client-ID and client-secret to the server.

Maybe your readme is even wrong. In fact I am not able to fetch the access token from the owncloud-app when I have the `code` and all the credentials. Neither with the method from the readme nor with the method of the RFC. I get the result

    {"message":"Current user is not logged in"}

**Comment by joneug** [comment]
Regarding client authentication: please have a look at [section 2.3](https://tools.ietf.org/html/rfc6749#section-2.3).

I don't think that the instructions in the readme are wrong. Please re-read and post details on your request if you still don't have luck.

**Comment by Krassmus** [comment]
Okay, maybe I don't get it. Here's my code after I received the `code` parameter:

        $client_id  = "mghfghfgh";
        $client_secret = ",jbm,gjf";
        $redirect_uri = "url";

        $payload = array(
            'grant_type' => "authorization_code",
            'code' => Request::get("code"),
            'redirect_uri' => $redirect_uri,
            'client_id' => $client_id,
            'client_secret' => $client_secret,
            'format' => "json"
        );

        $header = array();
        $header[] = "Accept: application/json";
        $header[] = "Authorization: Basic ".base64_encode($client_id . ":" .$client_secret);
        var_dump("Authorization: Basic ".base64_encode($client_id . ":" .$client_secret));

        $r = curl_init();
        curl_setopt($r, CURLOPT_URL, $owncloud."index.php/apps/oauth2/authorize?grant_type=authorization_code&code=".urlencode(Request::get("code"))."&redirect_uri=".urlencode($redirect_uri));
        //curl_setopt($r, CURLOPT_URL, $owncloud."index.php/apps/oauth2/authorize");
        curl_setopt($r, CURLOPT_POST, 1);
        curl_setopt($r, CURLOPT_HTTPHEADER, studip_utf8encode($header));
        curl_setopt($r, CURLOPT_RETURNTRANSFER, 1);

        curl_setopt($r, CURLOPT_POSTFIELDS, $payload);

        $result = curl_exec($r);
        $curl_info = curl_getinfo($r);
        curl_close($r);
        var_dump($curl_info);
        var_dump($result);`

As I said the $result is `{"message":"Current user is not logged in"}`. And $curlinfo is

    array(26) {
        ["url"]=>
      string(302) "https://server3.data-quest.de/rasmusowncloud/index.php/apps/oauth2/authorize?grant_type=authorization_code&code=6sNDcgbD7X5dFMZSDCmHMG7RgmGAnjrwlF5hyhbpPyHJSfFbyLdAgBCpcgt6IkH1&redirect_uri=https%3A%2F%2Fserver3.data-quest.de%2Fstudip_files%2Fplugins.php%2Fowncloudplugin%2Foauth%2Freceive_access_token"
        ["content_type"]=>
      string(31) "application/json; charset=utf-8"
        ["http_code"]=>
      int(401)
      ["header_size"]=>
      int(1079)
      ["request_size"]=>
      int(670)
      ["filetime"]=>
      int(-1)
      ["ssl_verify_result"]=>
      int(0)
      ["redirect_count"]=>
      int(0)
      ["total_time"]=>
      float(0.036513)
      ["namelookup_time"]=>
      float(2.0E-5)
      ["connect_time"]=>
      float(7.6E-5)
      ["pretransfer_time"]=>
      float(0.004014)
      ["size_upload"]=>
      float(944)
      ["size_download"]=>
      float(43)
      ["speed_download"]=>
      float(1177)
      ["speed_upload"]=>
      float(25853)
      ["download_content_length"]=>
      float(43)
      ["upload_content_length"]=>
      float(944)
      ["starttransfer_time"]=>
      float(0.004029)
      ["redirect_time"]=>
      float(0)
      ["redirect_url"]=>
      string(0) ""
        ["primary_ip"]=>
      string(11) "78.47.9.104"
        ["certinfo"]=>
      array(0) {
        }
      ["primary_port"]=>
      int(443)
      ["local_ip"]=>
      string(11) "78.47.9.104"
        ["local_port"]=>
      int(56443)
    }

**Comment by Krassmus** [comment]
No idea? Maybe my owncloud is misconfigured?

**Comment by Dagefoerde** [comment]
What happens if you remove  `studip_utf8encode` in
`    curl_setopt($r, CURLOPT_HTTPHEADER, studip_utf8encode($header));`
? 
I think it's not useful to explicitly utf8-encode headers and maybe this even introduces something that's wrong. If you have non-ascii characters in individual header fields then you could explicitly encode just them, but I would first try without.

**Comment by Krassmus** [comment]
Thank you. I tried it out, but it didn't change anything. `{"message":"Current user is not logged in"}` 
The headers have actually no non-ascii characters since client_id and client_secret get base64 encoded.

**Comment by joneug** [comment]
Sorry for the delay. 

Please use the Access Token URL `/index.php/apps/oauth2/api/v1/token` for requesting an Access Token as indicated in the Readme. The Authorization URL is only for requesting an Authorization Code.

**Comment by DeepDiver1975** [comment]
please reopen if issue is still valid

**Comment by Krassmus** [comment]
Yes, that works now. I must have been blind there. Thanx for having a look!
