### ISSUE TITLE
Clicking "Cancel" on the authorize page does not notify the client.

### ISSUE THREAD

**Issue by ogoffart** [owncloud/oauth2#46]
The page showing the dialog with the message `Do you really like to authorize the application “Desktop Client”?` has a Cancel button.
Clicking on it currently goes to the owncloud homepage
The problem is that it does not notify the client that the user canceled.
Perhaps we should redirect to   $redirect_uri/cancelled  or something similar instead, so the client can act appropriately

**Comment by pmaier1** [comment]
@felixboehm @PVince81 please find assignment and move to 'development' milestone then
