### ISSUE TITLE
Entering the wrong password once break the authentication flow

### ISSUE THREAD

**Issue by ogoffart** [owncloud/oauth2#47]
When the client open a browser to the `authorize` endpoint, if the browser was not logged in before, the user is shown the login dialog.

If the user enter the right password at the first attempt, everything is fine.

But if the user enter the wrong password at the first attempt, then enter the right password in a following attempt,  the user gets to the home owncloud page and cannot authenticate the client

### Steps to reproduce

1. Make sure that you are logged **out** of owncloud in the browser.
2. Use the client or something else that logs with OAuth. 
3. On the login page, enter the wrong password. Observe that the parametter in the URL change
4. Then enter the right password
5. Get redirected to the homepage instead of being able to accept the client. :-1:

**Comment by ogoffart** [comment]
This might actually be a bug with the owncloud login page. Perhaps I should have reported it in the core repo instead?

cc @DeepDiver1975

**Comment by ogoffart** [comment]
Reported as  https://github.com/owncloud/core/issues/28129

**Comment by pmaier1** [comment]
@felixboehm @PVince81 please find assignment and move to 'development' milestone then

**Comment by DeepDiver1975** [comment]
yes - core issue -> close
