### ISSUE TITLE
Being able to specify the user name in the `authorize` call

### ISSUE THREAD

**Issue by ogoffart** [owncloud/oauth2#48]
When the client is configured and needs to re-authenticate. It must re-authenticate with a given user.  It would be nice if we could pass the login as a parameter to the `authorize` call which is the URL we open the browser with.

The username could be used to pre-complete the user field of the login page.
And if the username does not match the currently logged-in user, the page should show an error telling the user to log out and log in as a different user.

**Comment by pmaier1** [comment]
Yes, please. Mainly the account check is very important, pre-completion would be nice!

- [ ] User name pre-completion
- [ ] Check if currently logged in user equals the user account that the application wants to authorize with

**Comment by butonic** [comment]
like this: https://demo.owncloud.org/index.php/login?user=demo

we could probably replace the username input field with a label and an additional change user link?

**Comment by ogoffart** [comment]
@butonic  yes, like that, but from the oauth `apps/oauth2/authorize` endpoint.

**Comment by ogoffart** [comment]
More details:

The client would send the browser to:

`index.php/apps/oauth2/authorize?response_type=code&client_id=[xxx]&redirect_uri=http://localhost:34413&user=ogoffart`

(the `user=` parameter would be optional)

 - If the user is not yet logged in, we should redirect to the login page, and ideally the user should be pre-entered, and it should not even possible to edit the user.

 - If another user is already logged in, instead of asking to authorize, we should have another dialog that let the user log out, then re-login as the right user, so he can accept the client.

**Comment by ogoffart** [comment]
Also, even if the `user` param was left empty (i.e., called from the wizard when the user was not set),
it would be nice if the "Do you really like to authorize the application “Desktop Client”?" message would add a button "log in as a different user" button, which would logout and imediatlye redirect to `index.php/login?redirect_url=<authorize url with all its parameters>`

**Comment by DeepDiver1975** [comment]
@ogoffart is there a client patch in place to submit the user? THX

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2017-07-14 14-26-46](https://user-images.githubusercontent.com/1005065/28212193-8fe5bf74-68a0-11e7-94c5-dd6d06f39b19.png)

Draft of the switch user screen @pmaier1 @ogoffart @SamuAlfageme

**Comment by ogoffart** [comment]
@DeepDiver1975   you can test with https://github.com/owncloud/client/pull/5907
