### ISSUE TITLE
Provide a userinfo endpoint

### ISSUE THREAD

**Issue by Dagefoerde** [owncloud/oauth2#56]
If you add ownCloud(+oauth2) as an OAuth 2 service provider to a Moodle (3.3) installation, Moodle's OAuth API queries a `userinfo_endpoint` in order to obtain information about the authorising ownCloud user. This fails since such an endpoint does not exist. Although actually from the OpenID spec, such an endpoint is useful to find out who was just logged in. It is also useful to check whether an access token is still valid without actually performing an operation on files. :)

Specs for the userinfo endpoint: https://openid.net/specs/openid-connect-core-1_0.html#UserInfo (general) and https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse (response).

Elements of the response can be: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims, of which `sub` is a MUST (identifier of an ownCloud user; what do you suggest? ID or username?). Moodle currently relies on a username and an email being present in the userinfo response. I already found out that you do not necessarily know an email adress, so I reported this there: https://tracker.moodle.org/browse/MDL-59511. I would suggest that you add an email address if it is known, instead of mocking one.

**Comment by DeepDiver1975** [comment]
OCS route:
![bildschirmfoto von 2017-07-12 15-26-00](https://user-images.githubusercontent.com/1005065/28119822-7338b358-6716-11e7-984b-3da67294297f.png)

**Comment by DeepDiver1975** [comment]
another option is to use the webdav capabilities to get information about the current user - but this might be a bit overkill - this requires xml parsing ;-)

**Comment by Dagefoerde** [comment]
cloud/user looks (nearly) fine, will check! :+1:

**Comment by Dagefoerde** [comment]
Awesome, that'll do. No further endpoint required (for me). This should be sufficient, unless you'd ever want to be an OpenID provider. Thank you!

For future reference, this is my Moodle configuration. Accessing nested JSON values works with `-` as a path delimiter (not my idea ;) ).

![oc-endpoints](https://user-images.githubusercontent.com/432117/28122876-c37a322a-671f-11e7-9fcf-c33ddd9d1f6c.png)
![oc-mappings](https://user-images.githubusercontent.com/432117/28122877-c381f9a6-671f-11e7-8b51-a3101a0d89d4.png) 

Thanks for your help, this is resolved IMO.
