### ISSUE TITLE
Only one connection allowed

### ISSUE THREAD

**Issue by ogoffart** [owncloud/oauth2#64]
With OAuth2, you can have only one active connection per Registered clients, it seems.

Steps to reproduce:
Try to log in with two clients on different computer with the same account. 

Expected behavior: 
Both clients can be connected at the same time

Actual behavior:
Only one client stays connected. The other client is getting disconnected.

**Comment by guruz** [comment]
FYI @joneug for discussion

**Comment by DeepDiver1975** [comment]
@ogoffart anything of interest in the log files

**Comment by ogoffart** [comment]
Nothing relevent in the log files.

The only thing i see in the log file is:

```
{"reqId":"AnsNddZm849xGn13AAjn","level":2,"time":"2017-07-20T08:29:22+00:00","remoteAddr":"::1","user":"--","app":"core","method":"POST","url":"\/~owncloud\/index.php\/apps\/oauth2\/api\/v1\/token","message":"Login failed: 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69' (Remote IP: '::1')"}
```

But this happen also if there is only one client. So I guess that's normal.

**Comment by DeepDiver1975** [comment]
these lines here are removing any previously authorized client - https://github.com/owncloud/oauth2/blob/master/lib/Controller/PageController.php#L204-L206

@joneug was this done by intention? I see no issue in having multiple authorization codes ......

**Comment by joneug** [comment]
We did this because we were authorizing a single web application that was integrated into a single other web application. When dealing with ownCloud's sync clients I think there are two possible solutions:

* Allowing multiple access tokens per client and user.
* Letting the sync clients register themselves when logging in so that each sync client gets its own `client_id`.

What do you think?

**Comment by DeepDiver1975** [comment]
> Allowing multiple access tokens per client and user.

I'd prefer this one - registering one client _id per user per workstation is a bit overkill.
