### ISSUE TITLE
The login page do not suggest the user despite the `user=` in the URL

### ISSUE THREAD

**Issue by ogoffart** [owncloud/oauth2#66]
Going to
`index.php/apps/oauth2/authorize?response_type=code&client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&redirect_uri=http://localhost:44783&user=alice`

Redirects to 

`index.php/login?redirect_url=%252F%257Eowncloud%252Findex.php%252Fapps%252Foauth2%252Fauthorize%253Fresponse_type%253Dcode%2526client_id%253DxdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69%2526redirect_uri%253Dhttp%253A%252F%252Flocalhost%253A44783%2526user%253Dalice`

Which does not pre-fill the username  (and ideally makes it read-only)

I suppose the same trick as the one used in 9400b663c9854c073a1ca06f1ea01428a496350b should be done to see the `user=` parametter in the redirect_url

**Comment by SamuAlfageme** [comment]
Exactly, forgot to mention this some days ago while testing out the multi-account flow in the client after https://github.com/owncloud/oauth2/pull/60. The option for current sessions works perfectly fine but when loading the login form is completely ignored.

**Comment by DeepDiver1975** [comment]
this requires a core change - https://github.com/owncloud/core/pull/28255

can you please test this with latest core master? THX

**Comment by ogoffart** [comment]
Problem still existing with the latest master.
This is not related to entering wrong password. Just getting the login screen for the first time if we are not logged already.

**Comment by SamuAlfageme** [comment]
@DeepDiver1975 yup, as @ogoffart says, can't see it working 😕 

![login_as_user](https://user-images.githubusercontent.com/2644445/28709938-8ee9c61e-7382-11e7-9532-77254bff522b.gif)

**Comment by DeepDiver1975** [comment]
damn shit ... I'll take care of this next week - thx for testing

**Comment by SamuAlfageme** [comment]
Possible https://github.com/owncloud/oauth2/pull/60 regression, since the other path seems to be also affected: 

![wrong_user](https://user-images.githubusercontent.com/2644445/28715741-b5db6ff4-7399-11e7-9614-1f0d94babd0b.gif)

**Comment by DeepDiver1975** [comment]
wtf! friday just killed is all ... I'll fix this on monday ...

**Comment by DeepDiver1975** [comment]
Ah - this is a client error page .....
