### ISSUE TITLE
[Regression] "Logout and login as <user>" on the authorization page is performing the protocol redirection

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/oauth2#68]
... instead of the redirection to a new login page. Continuation of https://github.com/owncloud/oauth2/issues/66#issuecomment-318630069

### Steps to reproduce:
1. Create an OAuth account on the Desktop client with the `user A`
2. Logout on the browser and log in as `user B`
3. Logout on the Desktop client and log-in back  

### Actual Behavior  

The "Switch User" application's dialogue is displayed with the option to `"Logout and login as <user>"` as described in https://github.com/owncloud/oauth2/issues/48#issuecomment-315347435, linking to `<server>/index.php/apps/oauth2/logout?user=<user>&requesttoken=<token>&response_type=code&client_id=<client_id>&redirect_uri=<redirect_url>`

When clicking the button however, **the user is redirected to `<redirect_url>/?code=<authorization_code>`**, which is interpreted by the client as the protocol redirection and used to:

```
curl \
[...] \
-H 'Content-Type:application/x-www-form-urlencoded' \
-X POST '<server>/index.php/apps/oauth2/api/v1/token' \
--data-binary 'grant_type=authorization_code&code=<authorization_code>&redirect_uri=<redirect_url>'
```
... and replied:

```
{
    "access_token": "<access_token>",
    "expires_in": 3600,
    "message_url": "<server>/index.php/apps/oauth2/authorization-successful",
    "refresh_token": "<refresh_token>",
    "token_type": "Bearer",
    "user_id": "<user B>"
}
```

The client then **detects the user mismatch and displays an error page** (see https://github.com/owncloud/client/blob/50874eecfab50c626b0d00b46afa178f0c5b8184/src/gui/creds/oauth.cpp#L119-L126) 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/28715741-b5db6ff4-7399-11e7-9614-1f0d94babd0b.gif"/>
</p>

### Expected Behavior 

When clicking in `<server>/index.php/apps/oauth2/logout?user=<user>&requesttoken=<token>&response_type=code&client_id=<client_id>&redirect_uri=<redirect_url>`, the user should be redirected to the login form:
- Preserving all the query parameters
- Displaying the OAuth2 notice from https://github.com/owncloud/oauth2/issues/43 
- Performing the `<redirect_url>/?code=<authorization_code>` redirection **only on successful login**

**Comment by DeepDiver1975** [comment]
reproduced - working on a fix ....
