### ISSUE TITLE
Show confirmation dialogue when deleting a registered client

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/oauth2#73]
Right now, clicking the "Delete" button does not prompt confirmation and there's no way of inserting the exact same tokens but messing with the DB.

![deleting_clients](https://user-images.githubusercontent.com/2644445/28871224-f4ecdae6-7783-11e7-934d-76ccd885c403.gif)

cc/ @DeepDiver1975 to consider this. No priority.

**Comment by DeepDiver1975** [comment]
Which browser is this?

There is a confirmation for me using chrome ....

**Comment by SamuAlfageme** [comment]
@DeepDiver1975 oh, lulz, it's Firefox 54.0.1 actually; will post a cross-browser table here reporting on the different behaviors.

**Comment by DeepDiver1975** [comment]
this is where the confirmation is being popped up - https://github.com/owncloud/oauth2/blob/master/js/settings.js#L25

**Comment by SamuAlfageme** [comment]
@DeepDiver1975 looks like Firefox is the only one with problems with `preventDefault`: https://stackoverflow.com/questions/1367195/preventdefault-wont-work-on-firefox

| Browser                | Result | Confirmation? |
|:----------------------:|--------|:-------------:|
| Mozilla **Firefox** 54.0.1 | ![deleting_clients](https://user-images.githubusercontent.com/2644445/28871224-f4ecdae6-7783-11e7-934d-76ccd885c403.gif) | ❌ |
| Google **Chrome** 60.0     | ![chrome](https://user-images.githubusercontent.com/2644445/28911723-c92d4f04-7831-11e7-9a95-0d697e53962f.gif) | ✅ |
| **Safari** 10.1.1          | ![safari](https://user-images.githubusercontent.com/2644445/28911717-c6a8858c-7831-11e7-8e6b-09e3479d10af.gif) | ✅ |
| Internet **Explorer** 11.10 | ![explorer](https://user-images.githubusercontent.com/2644445/28912298-0052122e-7834-11e7-9ad3-f7b059b98f04.gif) | ✅ |
| MS **Edge**  39.15  | ![edge](https://user-images.githubusercontent.com/2644445/28912326-13524dc6-7834-11e7-8448-d62072bb2ac7.gif) | ✅ |
