### ISSUE TITLE
Accounts from the LDAP user backend get replied with the UUID as user_id on the authorize call

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/oauth2#74]
The authorize call:

```
curl \ 
[...] \
-H 'Content-Type:application/x-www-form-urlencoded' \
-X POST 'https://<server>/index.php/apps/oauth2/api/v1/token' \
--data-binary 'grant_type=authorization_code&code=<code>&redirect_uri=<redirecrtion_url>'
```

... on an LDAP backed account is getting replied:

```
{
    "access_token": "<access_token>",
    "expires_in": 3600,
    "message_url": "https://<server>/index.php/apps/oauth2/authorization-successful",
    "refresh_token": "<refresh_token>",
    "token_type": "Bearer",
    "user_id": "b8df1298-8742-1034-8cb4-39af73a96b9a"
}
```

Notice the **`"user_id": "b8df1298-8742-1034-8cb4-39af73a96b9a"`** taking LDAP's UUID instead of the display name. It will be used instead the display_name in the client with all the effects:

![client_uuid](https://user-images.githubusercontent.com/2644445/28910756-695908dc-782e-11e7-976c-616a284e7ff0.png)

... but not that severe since the user supports it in the `user` query parameter:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/28911213-28938942-7830-11e7-8f07-a7736ed4406d.png"/>
</p>

See https://github.com/owncloud/client/issues/5413 -> https://github.com/owncloud/client/commit/084146756bb9637ef32f229281d053394389efc1

**Comment by DeepDiver1975** [comment]
> Notice the "user_id": "b8df1298-8742-1034-8cb4-39af73a96b9a" taking LDAP's UUID instead of the display name. It will be used instead the display_name in the client with all the effects:

this is okay from my pov - only the user_id is the true unique identifier we can rely on.

regarding the display to the user we better switch over to the display name

**Comment by SamuAlfageme** [comment]
> regarding the display to the user we better switch over to the display name

Should we include an additional parameter in the reply to use in the clients?

Also, note that you cannot login to ownCloud using the normal flow after:

![uuid](https://user-images.githubusercontent.com/2644445/28912032-c6d41052-7832-11e7-86db-04c884453d43.gif)

(you can edit the `user` query parameter in the URL though but it's a bit obscure to the average user)

**Comment by SamuAlfageme** [comment]
@DeepDiver1975 

> Should we include an additional parameter in the reply to use in the clients?

I tried to incorporate the request the clients (see e.g. https://github.com/owncloud/android-library/blob/master/src/com/owncloud/android/lib/resources/users/GetRemoteUserInfoOperation.java) use for SAML setups to get a valid username as an extra request after being authorized but:

```
$ curl -X GET 'https://<server>/ocs/v1.php/cloud/user?format=json'

{
    "ocs": {
        "meta": {
            "status": "ok",
            "statuscode": 100,
            "message": "OK",
            "totalitems": "",
            "itemsperpage": ""
        },
        "data": {
            "id": "b8df1298-8742-1034-8cb4-39af73a96b9a",
            "display-name": "aaliyah adams",
            "email": null
        }
    }
}
```

**See the underscore difference between the username we use to log in and the `display-name` returned by the ocs endpoint**: the display-name doesn't work to login. 

cc/ @ogoffart

**Comment by DeepDiver1975** [comment]
bääääh - so we are back in the loginname vs user-id stuff ....

**Comment by ogoffart** [comment]
I did not know about the `display-name` property, and I could indeed use that in the client UI.
But please, in make sure the `user-id` field in the oauth's token reply is whatever we need to use as  `user=` in the authorize call.

**Comment by SamuAlfageme** [comment]
@ogoffart see https://github.com/owncloud/client/blob/master/src/gui/creds/shibboleth/shibbolethuserjob.cpp#L38

**Comment by DeepDiver1975** [comment]
Okay - there are multiple login names for one user is - so in the ldap scenario we simply cannot preset the login screen.

Proposal:
- remove the readonly mode from the username on the login screen - this will allow the user to change the loginname
- instead of the user id (which is user unfriendly guid for ldap) we show the display name (user id on hover maybe ?)
- the user id will be kept in all api calls since this is the unique identifier

**Comment by PVince81** [comment]
@jvillafanez any ideas ?

**Comment by PVince81** [comment]
@jvillafanez assigning you mostly for the LDAP login thing, if you could help this sorted out somehow

**Comment by jvillafanez** [comment]
I'd go with @DeepDiver1975 's approach.

Don't count on LDAP to fetch the login name because it has several problems:
* There could be more than 1 valid login name for each user because they can login with the uid, mail, or any other attribute.
* If we ever try to fetch the login name, we'll need to parse the raw ldap filter. If we're lucky enough to get the filter without the "uid" placeholder being substituted we'll have to somehow extract the attribute. We'll have to rely on regular expresions, which will be error prone.

The assumption that the user_id is the same as the login name is wrong, and I don't think we have any support to store / fetch login names

**Comment by SamuAlfageme** [comment]
@jvillafanez 

> because they can login with the **uid** 

problem is they can't; see https://github.com/owncloud/oauth2/issues/74#issuecomment-319898504 - this issue will be solved if they could. We could (from a client POV just display the `display_name` from the ocs endpoint)

Would it be _overload_ to also allow login with LDAP UUIDs and embrace what @DeepDiver1975 says in https://github.com/owncloud/oauth2/issues/74#issuecomment-320248599 ?

> instead of the user id (which is user unfriendly guid for ldap) **we show the display name (user id on hover maybe ?)**

**Comment by jvillafanez** [comment]
> because they can login with the uid

I meant the ldap uid attribute, not the owncloud user's uid. As far as LDAP is concerned, you can set up your telephone number to be the login attribute and use it to login in ownCloud.

**Comment by SamuAlfageme** [comment]
@jvillafanez I mixed 'em up, my bad. Summing up, we need to get something that can be used to both:

- **Determine if the user being passed as query param. and the one returned by the auth. endpoints are the same** 
- And auto-fill the login form.

**Comment by michaelstingl** [comment]
@SamuAlfageme I found similar behaviour with SAML and OAuth2 and my question would be, does it behave different than direct SAML authentication without OAuth2?

**Comment by tomneedham** [comment]
Read through this ticket as I have been trying to assist @michaelstingl with an account here. Can we return the oc user_id and display_name to the client? Then we have to login with the user_id at the login screen, but maybe show the dispalyname to the user to make this more userfrienly - as @DeepDiver1975 proposes.

What do we need to do to achieve this? 
 - [ ] return user_id and display_name to the client
 - [ ] have the oauth js show a dummy display_name in the login form but actually use the supplied query param

Makes sense?

**Comment by DeepDiver1975** [comment]
All we can do is to use the displayname anywhere in the ui. We dont know the login name in case of ldap. From my understanding there is no need to pass additional information around between clients and server.

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2017-10-05 13-58-13](https://user-images.githubusercontent.com/1005065/31226132-4582a03e-a9d5-11e7-9b93-a8247da1ee1f.png)

far from perfect ...

**Comment by tomneedham** [comment]
Hide userid completely here?

**Comment by DeepDiver1975** [comment]
> Hide userid completely here?

I'm trying to move the user id to a tool tip - it might five valuable information to distinguish users.

**Comment by DeepDiver1975** [comment]
... or maybe the email address?

**Comment by DeepDiver1975** [comment]
![imageedit_2_4715418700](https://user-images.githubusercontent.com/1005065/31228429-cedaa130-a9dd-11e7-80b0-5cca49afb18c.png)
