### ISSUE TITLE
Change error message when logged in as wrong user

### ISSUE THREAD

**Issue by pmaier1** [owncloud/oauth2#76]
Should say: "You are logged in as '**user**' but the application requested access for user '**user**'. Please switch to the requested user using the button below to continue the authorization process."

If this is too long, drop the second sentence.

Thanks!

**Comment by PVince81** [comment]
steps to reproduce for people who don't know anything about this app ?

**Comment by PVince81** [comment]
@SamuAlfageme if you know how to reproduce it, would you be able to adjust the message in the code and test ? Assuming this is just a simple text change

**Comment by SamuAlfageme** [comment]
@pmaier1 actually, current string: https://github.com/owncloud/oauth2/blob/cd74d01635edb174d130f54834c66d523f39dc45/templates/switch-user.php#L27

... is more or less what you suggested:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/30120684-db96c4aa-9329-11e7-9b15-01e31db23768.png"/>
</p>

I think it's pretty clear as it is, no?

**Comment by pmaier1** [comment]
The message has a typo "You are logged as" (the 'in' is missing) and it could be easier understandable for non-technical users. I had a chat with @DeepDiver1975 some time ago and opened this ticket as a reminder for him to change that message.

**Comment by pmaier1** [comment]
I would have changed it myself but didn't know how to make parts of the text bold so I gave up :) making it bold is not that important in the end..

**Comment by SamuAlfageme** [comment]
@pmaier1 oh, I see. Did not notice the typo and the bold text in your example. 

@DeepDiver1975 @PVince81 is there an easy & elegant way to make a translatable string, such as:

```
<?php p($l->t('You are logged in as %s but the application requested access for user %s.', [$_['current_user'], $_['requested_user']])); ?>
```

... contain `<strong>` HTML tags to wrap the usernames?

**Comment by DeepDiver1975** [comment]
> HTML tags to wrap the usernames?

not really. p() will escape any html tags. using unescaped_print() is discouraged - it opens doors to sec issues .....

**Comment by PVince81** [comment]
"You are logged in as ') DROP TABLES https://xkcd.com/327/"

**Comment by Peter-Prochaska** [comment]
@PVince81 that doesn't work. There are no html tags inside, but if your username is "<script>here is the bad code</script>. That would work ;-)

**Comment by PVince81** [comment]
@DeepDiver1975 can you take care of this ?

**Comment by DeepDiver1975** [comment]
I can easily add the 'in' - but the styling remains tricky ...maybe later ...

**Comment by pmaier1** [comment]
> I can easily add the 'in' - but the styling remains tricky ...maybe later ...

Making user names bold is not that important IMO. A clear separation from the rest of the text is, IMO.
If making it bold means effort, I would be totally fine with: "You are logged in as '<user_x>' but the application requested access for user '<another_user>'. Please switch to the requested user using the button below to continue the authorization process."

**Comment by DeepDiver1975** [comment]
@pmaier1 please see #90 -  bold is now there ..

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2017-10-09 20-20-19](https://user-images.githubusercontent.com/1005065/31352509-4bb1e5ca-ad2f-11e7-858d-109e171d0a37.png)

**Comment by pmaier1** [comment]
Great, thanks! To provide a little more annoyance, can we have it like this: '**user**' (just adding ' before and after the bold user name)? :)

**Comment by DeepDiver1975** [comment]
what about using proper quotes - https://en.wikipedia.org/wiki/Guillemet

if I'm not miss taken single and double quotes are very technical - from a human language point of view Guillement might fit better

 @felixheidecke @settermjd opionions?

for sure this is something which needs to be addressed all over the platform properly

**Comment by pmaier1** [comment]
For me Guillemet looks very technical and I like the apostrophes from a style POV. Open for other opinions of course.

**Comment by DeepDiver1975** [comment]
> For me Guillemet looks very technical

I was search the web - but could not find it: the debian german translation guideline specifies that Guillements are to be used for any double quote in the source text .... anyway ...

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2017-10-09 21-54-16](https://user-images.githubusercontent.com/1005065/31355930-6d418cc4-ad3c-11e7-9ba5-4ff57160a6ee.png)

with single quotes now ...

**Comment by felixheidecke** [comment]
![31355930-6d418cc4-ad3c-11e7-9ba5-4ff57160a6ee](https://user-images.githubusercontent.com/12717530/31381498-08691f5a-adb5-11e7-99fc-5fd6fa57c8ea.png)

Unnecessary text is unnecessary. Who wrote this in the first place? :tongue:

**Comment by DeepDiver1975** [comment]
@pmaier1 @felixheidecke in order to not change this again and again - please talk to each other and decide. THX

**Comment by pmaier1** [comment]
I thought to make it a little easier to understand for unexperienced users but it's kind of unnecessary, yes.
Please do it as @felixheidecke suggested
- Delete second paragraph
- Change button text to "Switch users to continue"
