### ISSUE TITLE
OAuth2 authorization process is skipped after entering a wrong password

### ISSUE THREAD

**Issue by davigonz** [owncloud/oauth2#81]
### Steps to reproduce
1. Open in a browser an url like the one below (used in clients to initialize OAuth2 authentication method).

**https://oc_server/index.php/apps/oauth2/authorize?response_type=code&redirect_uri=oc://whatever.owncloud.com&client_id=whatever**

![screen shot 2017-08-18 at 11 13 52](https://user-images.githubusercontent.com/15261363/29452357-5b03de2c-8406-11e7-81a1-88bf0566c90c.png)

2. Introduce username with a wrong password. Url changes and does not take into account the OAuth authorization proccess any more.

![screen_shot_2017-08-18_at_11_16_49](https://user-images.githubusercontent.com/15261363/29452503-e501b0e0-8406-11e7-9fd5-ba1e2968fcda.png)

3. Introduce username with the right password.
4. Login is successful and the files view appears.

### Expected behaviour
Url with authorize button is loaded

![screen shot 2017-08-18 at 11 21 43](https://user-images.githubusercontent.com/15261363/29452708-a1e9902e-8407-11e7-9152-73c04c41bcc0.png)

### Actual behaviour
Basic login is triggered without asking again for OAuth2 authorization, looking pretty weird in mobile devices:

![screenshot_20170818-112906](https://user-images.githubusercontent.com/15261363/29453013-83f5140c-8408-11e7-8ace-a7f87abcaaa4.png)

### Server configuration
**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** php7.0.18

**ownCloud version:** 10.0.2

CC @davivel @nasli @jesmrec

**Comment by SamuAlfageme** [comment]
Duplicated of https://github.com/owncloud/oauth2/issues/47 and fixed on
core master. cc/ @davigonz
-- 

<http://www.solidgeargroup.com/> *Samuel Alfageme Sainz*
QA Engineer

(+34) 983 114 214
  salfageme@solidgeargroup.com
solidgeargroup.com <http://www.solidgeargroup.com/>  |
<https://es-es.facebook.com/solidgearsl>
<https://twitter.com/solidgeargroup>
<https://www.linkedin.com/company/solidgear-sl>

**Comment by davigonz** [comment]
Thanks @SamuAlfageme , I close it then
