### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by pmaier1** [owncloud/oauth2#82]
Please add a changelog to this repository logging changes version-wise as far as possible.

- [x] Add CHANGELOG.md
- [x] Stick to the keepachangelog structure proposed and implemented by @PVince81 in core and e.g. https://github.com/owncloud/customgroups/blob/master/CHANGELOG.md

There's a script to compile the changelog according to merged PRs. For apps it could also be easier to note down changes manually.

Thanks a lot!

@PVince81

**Comment by SamuAlfageme** [comment]
As suggested by @pmaier1 I'll add some known issues on the changelog once I've collected them.

**Comment by pmaier1** [comment]
Please add them to the release checklist https://github.com/owncloud/oauth2/issues/57 as we do it with core. Thanks!
