### ISSUE TITLE
Add another screenshot

### ISSUE THREAD

**Issue by pmaier1** [owncloud/oauth2#91]
I would like to add a screenshot with the OAuth2 logo and ownCloud logo as title screenshot.
@hurradieweltgehtunter can you take care for this, please?

**Comment by hurradieweltgehtunter** [comment]
why the ownCloud logo? We never had our own logo in the app images. Everywhere the app image gets displayed it is in an ownCloud context. I don't see the need inserting our logo.

some proposals:
![owncloud-app-oauth-2-2](https://user-images.githubusercontent.com/16665512/31485405-fb31870c-af33-11e7-81dd-28c450e86dc7.jpg)
![owncloud-app-oauth-2-3](https://user-images.githubusercontent.com/16665512/31485407-fb4ef418-af33-11e7-9d84-81d70def0a55.jpg)
![owncloud-app-oauth-2-4](https://user-images.githubusercontent.com/16665512/31485409-fb696a14-af33-11e7-998c-1fc74c207eca.jpg)
![owncloud-app-oauth-2](https://user-images.githubusercontent.com/16665512/31485410-fb83ca26-af33-11e7-81ac-50557a106111.jpg)

**Comment by michaelstingl** [comment]
All very cool - 1st and last one are my favorites

**Comment by pmaier1** [comment]
> why the ownCloud logo? We never had our own logo in the app images

Good point, agreed. Well, all of them are very nice, thanks! I like the second one most. Would go for a PR now. We can change it until it's merged.

**Comment by pmaier1** [comment]
Preliminary PR https://github.com/owncloud/oauth2/pull/93

**Comment by jnweiger** [comment]
last one is best, imho.

**Comment by butonic** [comment]
third one looks most like armor.

**Comment by pmaier1** [comment]
Most votes for 4 (also on other channels). Adjusted.

**Comment by pmaier1** [comment]
PR merged.
