### ISSUE TITLE
Define and implement access token scopes 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/oauth2#96]
See: https://github.com/owncloud/oauth2/#possible-improvements -> https://tools.ietf.org/html/rfc6749#section-3.3 

Once implemented we could take advantage of these in application password generation or vice-versa* (see e.g. GitHub's https://help.github.com/assets/images/help/settings/token_scopes.gif or https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html)

*: generating an application password with a particular set of scopes should be the more or less equal to an access_token with those, the second having an additional predefined expiration time.

**Comment by tomneedham** [comment]
Some good discussion about that here https://github.com/owncloud/core/issues/10400

**Comment by WisdomSky** [comment]
any updates?

**Comment by DeepDiver1975** [comment]
I think we can close this. The owncloud 10 series will no get this. The owncloud infinite scale project will come with innovations like this.
