### ISSUE TITLE
Can't seem to access ocsapp endpoints (cloud/user)

### ISSUE THREAD

**Issue by Dagefoerde** [owncloud/oauth2#99]
I need to access the `cloud/user` OCS endpoints to obtain user details of the authenticated user (required e.g. by Moodle for connecting system accounts). Accessing `ocsapp/cloud/user` works in a logged-in browser, but not in OAuth 2 bearer token authenticated requests. I can see a `401` status code  from the log, but can't seem to find a more explanatory error message. 

Is it possible that core does not check OAuth authentication for such requests?

(Side note: finding `/ocsapp` was unnecessarily hard, did I miss important documentation? I considered that maybe I looked in the wrong places, but on the other hand there is https://doc.owncloud.org/server/10.0/developer_manual/core/ocs-capabilities.html , which clearly has an outdated URL...)

ownCloud: 10.0.3; oauth2 app: 0.2.0.

**Comment by DeepDiver1975** [comment]
> (Side note: finding /ocsapp was unnecessarily hard, did I miss important documentation? I considered that maybe I looked in the wrong places, but on the other hand there is https://doc.owncloud.org/server/10.0/developer_manual/core/ocs-capabilities.html , which clearly has an outdated URL...)

this is for sure still the correct URL - the ocsapp/cloud/user route is internal and should not be accessible from outside

**Comment by DeepDiver1975** [comment]
You can also use v2 to get proper http status back in case of errors


/ocs/v2.php/cloud/capabilities?format=json

**Comment by Dagefoerde** [comment]
Alright, sorry, I didn't explain. The reason why I called it "clearly outdated" is because – in an authenticated browser – it results in a 302:
`[Wed Nov 22 10:26:15 2017] 128.176.158.87:34170 [302]: /index.php/ocs/v2.php/cloud/capabilities?format=json` 
... and then redirects to http://172.17.0.1:8999/index.php/apps/files/ . Same for `cloud/user`. Then I found this https://github.com/owncloud/core/commit/394ba7dd387e6fdbb52eb50c9a43fb47c7465ff3#diff-aeff1dbcba1bef51455241c33c9cc3baL84 which looked as if the endpoints had been moved intentionally.

Anyway, `/ocs/v2.php/cloud/capabilities?format=json` does not work, neither with a browser session nor with a valid bearer token.

**Comment by DeepDiver1975** [comment]
> Then I found this owncloud/core@394ba7d#diff-aeff1dbcba1bef51455241c33c9cc3baL84 which looked as if the endpoints had been moved intentionally.

indeed - the implementation was move on purpose - but the route behavior ~is~ *should* still be the same.

I need to retest this.

**Comment by Dagefoerde** [comment]
I realised that I was on oC daily and that it could have been a temporary issue, but I just upgraded (see below) and re-tested it, but I still can't access the `cloud/*` endpoints in `/ocs/v2.php...`.

* ownCloud	10.0.4 RC1 (daily) Build:2017-11-29T04:08:44+00:00 a277026a993f935b8cb8667ebfcb7d910138e39d
* OAuth 2 app in version 0.2.1

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG we need an integration test on this - can you add that please? THX

**Comment by SergioBertolinSG** [comment]
We have tests for capabilities, but only using v1 right now. https://github.com/owncloud/core/blob/master/tests/integration/capabilities_features/capabilities.feature

**Comment by Dagefoerde** [comment]
In the context of this issue that doesn't matter. Both v1 and v2 don't work, i.e. they redirect to the files app immediately.

**Comment by DeepDiver1975** [comment]
@Dagefoerde any chance to dig deeper on your side?

Pure curl with bearer token as authentication header works fro me here

```sh
$ curl  -H "Authorization: Bearer abcdefgh" http://alien:8080/ocs/v2.php/cloud/capabilities?format=json | json_pp 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1153  100  1153    0     0    338      0  0:00:03  0:00:03 --:--:--   339
{
   "ocs" : {
      "meta" : {
         "statuscode" : 200,
         "message" : "OK",
         "status" : "ok",
         "totalitems" : "",
         "itemsperpage" : ""
      },
      "data" : {
         "version" : {

**Comment by Dagefoerde** [comment]
Not until today, sorry.
I installed a fresh 10.0.4 stable with the 0.2.1 oauth app. Weirdly enough, this worked effortlessly. I don't know what was the issue here, but probably it was mine. Sorry to bother, and thanks! :)
